### ISSUE TITLE
kinsta-mu-plugins installs files one level too deep with composer

### ISSUE THREAD

**Issue by claudio-uey** [shineunited/kinsta-mu-plugins#2]
Composer will install the plugins with the following structure:
- mu-plugins/
-- kinsta-mu-plugins/
--- kinsta-mu-plugins.php
--- kinsta-mu-plugins/
-- other-mu-plugins/
-- other-mu-plugins.php

The correct structure needs to be:
- mu-plugins/
-- kinsta-mu-plugins.php
-- kinsta-mu-plugins/
-- other-mu-plugins/
-- other-mu-plugins.php

**Comment by shineadmin** [comment]
Unfortunately composer must install packages into their own directories, and since WordPress looks for mu-plugins as files this won't work without modifications.

This package was intended for use in a [bedrock](https://roots.io/bedrock/) deployment, which relies on an autoloader to open directories and load the plugin files inside.
